# Enable select rules instead of all rules
lint.select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "S",   # flake8-bandit
    "RUF", # Ruff-specific rules
]

# Exclude some directories and files
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Target Python Version
target-version = "py38"

# Line length configuration
line-length = 120

# Sort imports
lint.isort.known-first-party = ["mmcp", "gerrit", "utils"]

# Ignore specific violations project-wide
lint.ignore = [
    "D203",    # One blank line required before class docstring
    "D212",    # Multi-line docstring summary should start at the first line
    "E501",    # Line too long (handled by formatter)
    "G004",    # Logging statement uses f-string
    "ANN101",  # Missing type annotation for `self` in method
    "ANN102",  # Missing type annotation for `cls` in classmethod
    "W293",    # Blank line contains whitespace
    "D213",    # Multi-line docstring summary should start at second line
    "B904",    # Use 'raise ... from err' in exception handlers
]

# Per-file ignores for specific directories/files
[lint.per-file-ignores]
"tests/**/*.py" = [
    "ANN",      # Type annotations
    "PT009",    # Use a regular assert instead of unittest-style assertion
    "S101",     # Use of assert detected
    "SIM117",   # Use a single with statement with multiple contexts
    "PGH003",   # Use specific rule codes when ignoring type issues
    "BLE001",   # Do not catch blind exception: Exception
    "D",        # Documentation rules
    "PLR2004",  # Magic value comparison
]

# Configure formatting options
[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
